
#pragma once

#include <gui_guider.h>   // generated by SquareLine

#include "UI/screen.hpp"


// FORWARD DECLARATIONS =====================================================================================

namespace APP::UI {

    // CONSTANTS ============================================================================================

    // MACROS ===============================================================================================

    // TYPES ================================================================================================

    // STATIC VARIABLES =====================================================================================

    // FUNCTION DECLARATION =================================================================================

    // TEMPLATE DECLARATION =================================================================================

    // CLASS DECLARATION ====================================================================================

    // @brief The main screen of the smartwatch – displays time, battery, and geometric decorations.
    class main_screen : public screen {
    public:

        main_screen();

        ~main_screen();

        void init() override;


        void show() override;


        void hide() override;


        void destroy() override {}


        void recreate_ui();


        lv_obj_t* get_root() override;


        // Event callback for this screen's widgets
        bool handle_event(lv_event_t* e) override;


        // @brief Set the clock time (used by NTP or manual setting).
        // @param time  New time (hours, minutes, seconds).
        static void set_clock(const APP::clock time);

    private:

        void create_ui_elements();


        // @brief Start the internal timer that updates the clock every second.
        void start_clock();


        // @brief Update the clock display (called every second by the timer).
        void update_clock();


        // @brief Draw decorative geometric elements on the screen (no longer used; kept for reference).
        void draw_decorations(lv_obj_t* parent);


        lv_ui                   m_ui;
        lv_obj_t*               m_hour_label   = nullptr;
        lv_obj_t*               m_minute_label = nullptr;
        lv_obj_t*               m_second_label = nullptr;
        lv_obj_t*               m_battery_label = nullptr;
        lv_obj_t*               m_time_label = nullptr;
        lv_obj_t*               m_battery_cont = nullptr;       // container for battery icon + percentage
        lv_obj_t*               m_battery_icon = nullptr;       // the battery symbol label
        lv_obj_t*               m_battery_pct_label = nullptr;  // percentage text overlay
        lv_obj_t*               m_pattern_canvas = nullptr;

        static APP::clock       m_clock;
        static constexpr u8     BATTERY_BUFFER_SIZE = 5;
        u8                      m_battery_buffer[BATTERY_BUFFER_SIZE] = {0};
        u8                      m_battery_index = 0;
        u8                      m_battery_count = 0;
    };

}
