
#pragma once

#include <gui_guider.h>   // generated by SquareLine

#include "UI/screen.hpp"


// FORWARD DECLARATIONS =====================================================================================

namespace APP::UI {

    // CONSTANTS ============================================================================================

    // MACROS ===============================================================================================

    // TYPES ================================================================================================

    // STATIC VARIABLES =====================================================================================

    // FUNCTION DECLARATION =================================================================================

    // TEMPLATE DECLARATION =================================================================================

    // CLASS DECLARATION ====================================================================================

    class main_screen : public screen {
    public:

        main_screen();

        ~main_screen();

        void init() override;
        
        void show() override;
        
        void hide() override;
        
        void destroy() override;
        
        lv_obj_t* get_root() override;

        // Event callback for this screen's widgets
        bool handle_event(lv_event_t* e) override;

    private:
    
        void start_clock();
        
        void update_clock();

        lv_ui                   m_ui;
        lv_obj_t*               m_hour_label   = nullptr;
        lv_obj_t*               m_minute_label = nullptr;
        lv_obj_t*               m_second_label = nullptr;
        lv_obj_t*               m_battery_label = nullptr;
        lv_obj_t*               m_time_label = nullptr; 

        APP::clock              m_clock{};
        static constexpr u8     BATTERY_BUFFER_SIZE = 5;   // window size
        u8                      m_battery_buffer[BATTERY_BUFFER_SIZE] = {0};
        u8                      m_battery_index = 0;
        u8                      m_battery_count = 0;
    };

}
