
#pragma once

#include <gui_guider.h>   // generated by SquareLine

#include "UI/screen.hpp"


// FORWARD DECLARATIONS =====================================================================================

namespace APP::UI {

    // CONSTANTS ============================================================================================

    // MACROS ===============================================================================================

    // TYPES ================================================================================================

    // STATIC VARIABLES =====================================================================================

    // FUNCTION DECLARATION =================================================================================

    // TEMPLATE DECLARATION =================================================================================

    // CLASS DECLARATION ====================================================================================

    class main_screen : public screen {
    public:

        main_screen();

        ~main_screen();

        void init() override;
        
        void show() override;
        
        void hide() override;
        
        void destroy() override;
        
        lv_obj_t* get_root() override;

        // Event callback for this screen's widgets
        bool handle_event(lv_event_t* e) override;

    private:
    
        void out_time(APP::clock_module* clock);

        void start_clock();
        
        void update_clock();

        lv_ui                   m_ui;   // holds all widgets
        APP::clock_module       m_clock{};
        lv_obj_t*               m_time_label = nullptr; 
        
    };

}
